import type { Metadata } from "next";
import "../styles/reset.scss";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import styles from "./layout.module.scss";
import { Provider } from "@/components/provider";

export const metadata: Metadata = {
  title: "Chop Logic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <Provider>
          <Header />
          <main className={styles.layout__main}>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
