import type { Metadata } from "next";
import "../styles/reset.scss";
import styles from "./layout.module.scss";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Chop Logic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <Header />
        <main className={styles.layout__main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
